# Generated by Django 3.0.5 on 2021-11-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='good',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='good_prob',
            field=models.IntegerField(default=0),
        ),
    ]
