# Generated by Django 3.0.5 on 2021-11-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_customer', '0002_auto_20211118_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_details',
            old_name='good',
            new_name='bad',
        ),
        migrations.RenameField(
            model_name='customer_details',
            old_name='good_prob',
            new_name='res_prob',
        ),
    ]
