# Generated by Django 3.0.5 on 2021-11-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_customer', '0003_auto_20211120_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='marital_status',
            field=models.CharField(max_length=150),
        ),
    ]
